### ISSUE TITLE
How is the max connection?

### ISSUE THREAD

**Issue by RobinsonLaw** [krylovsk/mqtt-benchmark#10]
2020/01/10 10:30:45 Starting client  252
2020/01/10 10:30:45 Starting client  253
2020/01/10 10:30:45 Starting client  254
2020/01/10 10:30:45 Starting client  255
2020/01/10 10:30:45 CLIENT 177 had error connecting to the broker: Network Error : dial tcp 52.221.235.39:1883: socket: too many open files
2020/01/10 10:30:45 CLIENT 176 had error connecting to the broker: Network Error : dial tcp 52.221.235.39:1883: socket: too many open files
2020/01/10 10:30:45 CLIENT 178 had error connecting to the broker: Network Error : dial tcp 52.221.235.39:1883: socket: too many open files
2020/01/10 10:30:45 CLIENT 175 had error connecting to the broker: Network Error : dial tcp 52.221.235.39:1883: socket: too many open files

**Comment by krylovsk** [comment]
Looks like you have exhausted the number of open sockets, which could be the limits of your environment.
What is your environment and what are the parameters you running the tool with?
