### ISSUE TITLE
How to subscribe?

### ISSUE THREAD

**Issue by DongGuangHui0707** [krylovsk/mqtt-benchmark#18]
I want to subscribe the topic. Does it support?

**Comment by krylovsk** [comment]
Hey @DongGuangHui0707 no the tool does not support subscribing to a topic, but that might be an interesting feature.

Could you explain the scenario you want to test in more detail?

**Comment by krylovsk** [comment]
Use mqtt client, e.g. mosquitto_sub: https://mosquitto.org/man/mosquitto_sub-1.html
