### ISSUE TITLE
Can't open more than ~200 outgoing for a single thread? mac os big sur 11.2 intel

### ISSUE THREAD

**Issue by Ashtonian** [krylovsk/mqtt-benchmark#19]
Hello, 

```
2021/03/12 19:19:32 CLIENT 2524 had error connecting to the broker: Network Error : dial tcp mymqttip:1883: socket: too many open files
```

Tryin to run with 10k connections and i start to get this pretty quick, any ideas what I need to do ? 

running on mac os big sur 11.2

**Comment by krylovsk** [comment]
Hey @Ashtonian looks like you are hitting the OS limit on open files. Try changing the limit with ulimit e.g. `ulimit -n 10240`.

**Comment by Ashtonian** [comment]
Thank you! That seems to have helped substantially! Now it seems to get up to 10k connections before it'll start erroring out, this time with i/on timeouts which I'm assuming are more about bandwidth.
