### ISSUE TITLE
Unable to install...

### ISSUE THREAD

**Issue by demian85** [krylovsk/mqtt-benchmark#21]
Sorry, I'm not a Go developer and the most basic instructions do not work.
On Mac, I ran:

```
- brew install go
- go install github.com/krylovsk/mqtt-benchmark@main
- ./mqtt-benchmark -h
``` 
There is no such file as `mqtt-benchmark` in this folder. Where is it?

Thanks.

**Comment by krylovsk** [comment]
It will be installed in `GOPATH`:

>If the environment variable is unset, GOPATH defaults to a subdirectory named "go" in the user's home directory ($HOME/go on Unix, %USERPROFILE%\go on Windows), unless that directory holds a Go distribution. Run "go env GOPATH" to see the current GOPATH.

https://golang.org/cmd/go/#hdr-GOPATH_environment_variable
