### ISSUE TITLE
Network Error : %!s(<nil>)

### ISSUE THREAD

**Issue by demian85** [krylovsk/mqtt-benchmark#22]
No idea what this is. I can successfully connect programmatically using a node.js script with the same parameters...
What's wrong?
```
./mqtt-benchmark --broker "tcp://staging.broker.aritronix.com:8883" --clients 1 --qos 1 --count 50 --username *** --password "***"
2021/06/30 10:31:23 Starting client  0
2021/06/30 10:31:24 CLIENT 0 had error connecting to the broker: Network Error : %!s(<nil>)
```
Thanks.

**Comment by demian85** [comment]
Does this support SSL/TLS?

**Comment by demian85** [comment]
Okay, NO. I disabled TLS and it works. But somehow I cannot test with 1000 clients, some of them return this error:
``` 2021/06/30 10:55:23 CLIENT 989 had error connecting to the broker: Network Error : dial tcp: lookup staging.broker.aritronix.com: no such host``` 
Is it because of the connection limits? I'm on Mac

**Comment by krylovsk** [comment]
The error looks like a DNS resolution problem. You might indeed be hitting the OS connections limit, see #19.
