### ISSUE TITLE
Add custom payload messages

### ISSUE THREAD

**Issue by tigerkitchen** [krylovsk/mqtt-benchmark#9]
Can I send custom payload messages?Includes strings and hexadecimal types

**Comment by krylovsk** [comment]
Can you explain the use case? Today the tool generates identical messages to stress test MQTT broker (each msg is a byte array of the configured size).

**Comment by tigerkitchen** [comment]
In fact, this is not the scope of MQTT server stress test, mainly to add custom messages to facilitate the test business system, the MQTT stress test seen so far does not support custom messages

**Comment by edoardesd** [comment]
I don't get the point of @tigerkitchen , but I don't think it's a difficult task.

Maybe more interesting, not add a custom text message, but the timestamp of beginning of the simulation or -even better- the timestamp of the moment when the message is sent.

**Comment by Misiu** [comment]
@krylovsk I also would like to be able to specify the payload of messages.
For example, I'd like to be able to send `{"temperature":10,"timeStamp":1597314150}` to topic `house/bedroom/temp`
I can specify the topic but not the payload.

I think this would be extremely helpful and it would help to test the whole infrastructure.
In my case, I'd like to check how the database will perform and my mechanism that subscribes to specific topics and stores the values in the database.

**Comment by Misiu** [comment]
@krylovsk @tigerkitchen added in https://github.com/krylovsk/mqtt-benchmark/pull/12

**Comment by Misiu** [comment]
I'm testing my PR right now.
Remember you must escape double-quotes.
This is my sample command:

`mqtt-benchmark --broker tcp://localhost:1883 --count 100 --clients 100 --qos 0 --username user --password pass --topic house/bedroom/temperature  --payload {\"temperature\":10,\"timeStamp\":1597314150}`

**Comment by krylovsk** [comment]
The PR is merged, closing this issue.

**Comment by Misiu** [comment]
@krylovsk thank you for merging my PR :)

**Comment by krylovsk** [comment]
Thanks for the contribution, @Misiu ! I was planning to do cleanup and tests for the v0.2, but nothing new functionally.
